#!/bin/sh

INSTALL_DIR=/usr/local/lib/python2.7/dist-packages
PTRACKS=ptracks

if [ -d $INSTALL_DIR/$PTRACKS ]; then
	rm -f /usr/local/lib/python2.7/dist-packages/ptracks
fi

ln -s `pwd`/ptracks /usr/local/lib/python2.7/dist-packages/ptracks

#
# /etc/ptracks
#

if [ -d /etc/$PTRACKS ]; then
	rm -rf /etc/ptracks
fi
sudo mkdir /etc/ptracks
ln -s `pwd`/data /etc/ptracks/data
ln -s `pwd`/tracks.cfg /etc/ptracks/tracks.cfg

#
# /etc/init.d/ptracks
#
rm -rf /etc/init.d/ptracks
ln -s `pwd`/bin/ptracks /etc/init.d/ptracks
