#!/bin/bash

#  nome do computador
HOST=`hostname`

#  diretório da aplicação
# cd ~/Public/wrk.srce/pTrack/atual

#  executa o editor da base de dados
#/usr/bin/env python -OO ./merlin.py 2> ./merlin.$HOST.log
/usr/bin/env python ./merlin.py 2> ./merlin.$HOST.log

#  diretorio raiz
# cd ~
