# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_aer_data_new.ui'
#
# Created: Wed Jun  1 12:00:03 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlgAerDataNEW(object):
    def setupUi(self, dlgAerDataNEW):
        dlgAerDataNEW.setObjectName(_fromUtf8("dlgAerDataNEW"))
        dlgAerDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        dlgAerDataNEW.resize(769, 608)
        dlgAerDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        dlgAerDataNEW.setSizeGripEnabled(True)
        dlgAerDataNEW.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(dlgAerDataNEW)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(dlgAerDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.wid_aer = QtGui.QWidget(self.splitter)
        self.wid_aer.setObjectName(_fromUtf8("wid_aer"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wid_aer)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtw_aer = QtGui.QTableWidget(self.wid_aer)
        self.qtw_aer.setObjectName(_fromUtf8("qtw_aer"))
        self.qtw_aer.setColumnCount(0)
        self.qtw_aer.setRowCount(0)
        self.verticalLayout.addWidget(self.qtw_aer)
        self.frm_aer_bbx = QtGui.QFrame(self.wid_aer)
        self.frm_aer_bbx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_aer_bbx.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_aer_bbx.setObjectName(_fromUtf8("frm_aer_bbx"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frm_aer_bbx)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_aer_new = QtGui.QPushButton(self.frm_aer_bbx)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_aer_new.setIcon(icon)
        self.btn_aer_new.setObjectName(_fromUtf8("btn_aer_new"))
        self.horizontalLayout_4.addWidget(self.btn_aer_new)
        self.btn_aer_del = QtGui.QPushButton(self.frm_aer_bbx)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_aer_del.setIcon(icon1)
        self.btn_aer_del.setObjectName(_fromUtf8("btn_aer_del"))
        self.horizontalLayout_4.addWidget(self.btn_aer_del)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bbx_aer = QtGui.QDialogButtonBox(self.frm_aer_bbx)
        self.bbx_aer.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbx_aer.setObjectName(_fromUtf8("bbx_aer"))
        self.horizontalLayout_4.addWidget(self.bbx_aer)
        self.verticalLayout.addWidget(self.frm_aer_bbx)
        self.wid_aer_data = QtGui.QWidget(self.splitter)
        self.wid_aer_data.setObjectName(_fromUtf8("wid_aer_data"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wid_aer_data)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frm_aer_id = QtGui.QFrame(self.wid_aer_data)
        self.frm_aer_id.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_aer_id.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_aer_id.setLineWidth(1)
        self.frm_aer_id.setObjectName(_fromUtf8("frm_aer_id"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frm_aer_id)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_aer_indc = QtGui.QLabel(self.frm_aer_id)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_aer_indc.sizePolicy().hasHeightForWidth())
        self.lbl_aer_indc.setSizePolicy(sizePolicy)
        self.lbl_aer_indc.setObjectName(_fromUtf8("lbl_aer_indc"))
        self.gridLayout_4.addWidget(self.lbl_aer_indc, 0, 0, 1, 1)
        self.txt_aer_indc = QtGui.QLabel(self.frm_aer_id)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_aer_indc.setFont(font)
        self.txt_aer_indc.setObjectName(_fromUtf8("txt_aer_indc"))
        self.gridLayout_4.addWidget(self.txt_aer_indc, 0, 1, 1, 1)
        self.lbl_aer_desc = QtGui.QLabel(self.frm_aer_id)
        self.lbl_aer_desc.setObjectName(_fromUtf8("lbl_aer_desc"))
        self.gridLayout_4.addWidget(self.lbl_aer_desc, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.qle_aer_desc = QtGui.QLineEdit(self.frm_aer_id)
        self.qle_aer_desc.setObjectName(_fromUtf8("qle_aer_desc"))
        self.gridLayout_4.addWidget(self.qle_aer_desc, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.frm_aer_id)
        self.gbx_arp = QtGui.QGroupBox(self.wid_aer_data)
        self.gbx_arp.setObjectName(_fromUtf8("gbx_arp"))
        self.gridLayout = QtGui.QGridLayout(self.gbx_arp)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_elev = QtGui.QLabel(self.gbx_arp)
        self.lbl_elev.setObjectName(_fromUtf8("lbl_elev"))
        self.gridLayout.addWidget(self.lbl_elev, 2, 0, 1, 1)
        self.lbl_lat = QtGui.QLabel(self.gbx_arp)
        self.lbl_lat.setMinimumSize(QtCore.QSize(140, 0))
        self.lbl_lat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lat.setObjectName(_fromUtf8("lbl_lat"))
        self.gridLayout.addWidget(self.lbl_lat, 0, 0, 1, 1)
        self.lbl_lng = QtGui.QLabel(self.gbx_arp)
        self.lbl_lng.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_lng.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lng.setObjectName(_fromUtf8("lbl_lng"))
        self.gridLayout.addWidget(self.lbl_lng, 1, 0, 1, 1)
        self.qle_lat = QtGui.QLineEdit(self.gbx_arp)
        self.qle_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_lat.setObjectName(_fromUtf8("qle_lat"))
        self.gridLayout.addWidget(self.qle_lat, 0, 1, 1, 1)
        self.sbx_elev = QtGui.QSpinBox(self.gbx_arp)
        self.sbx_elev.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_elev.setMaximum(5000)
        self.sbx_elev.setSingleStep(100)
        self.sbx_elev.setObjectName(_fromUtf8("sbx_elev"))
        self.gridLayout.addWidget(self.sbx_elev, 2, 1, 1, 1)
        self.lbl_decl = QtGui.QLabel(self.gbx_arp)
        self.lbl_decl.setObjectName(_fromUtf8("lbl_decl"))
        self.gridLayout.addWidget(self.lbl_decl, 3, 0, 1, 1)
        self.dsb_decl = QtGui.QDoubleSpinBox(self.gbx_arp)
        self.dsb_decl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_decl.setDecimals(1)
        self.dsb_decl.setMinimum(-90.0)
        self.dsb_decl.setMaximum(90.0)
        self.dsb_decl.setObjectName(_fromUtf8("dsb_decl"))
        self.gridLayout.addWidget(self.dsb_decl, 3, 1, 1, 1)
        self.qle_lng = QtGui.QLineEdit(self.gbx_arp)
        self.qle_lng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_lng.setObjectName(_fromUtf8("qle_lng"))
        self.gridLayout.addWidget(self.qle_lng, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.gbx_arp)
        self.gbx_pst = QtGui.QGroupBox(self.wid_aer_data)
        self.gbx_pst.setObjectName(_fromUtf8("gbx_pst"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.gbx_pst)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.qtw_pst = QtGui.QTableWidget(self.gbx_pst)
        self.qtw_pst.setObjectName(_fromUtf8("qtw_pst"))
        self.qtw_pst.setColumnCount(0)
        self.qtw_pst.setRowCount(0)
        self.verticalLayout_11.addWidget(self.qtw_pst)
        self.verticalLayout_2.addWidget(self.gbx_pst)
        self.frm_pst_bbx = QtGui.QFrame(self.wid_aer_data)
        self.frm_pst_bbx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_pst_bbx.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_pst_bbx.setObjectName(_fromUtf8("frm_pst_bbx"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frm_pst_bbx)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_pst_new = QtGui.QPushButton(self.frm_pst_bbx)
        self.btn_pst_new.setIcon(icon)
        self.btn_pst_new.setObjectName(_fromUtf8("btn_pst_new"))
        self.horizontalLayout_3.addWidget(self.btn_pst_new)
        self.btn_pst_del = QtGui.QPushButton(self.frm_pst_bbx)
        self.btn_pst_del.setIcon(icon1)
        self.btn_pst_del.setObjectName(_fromUtf8("btn_pst_del"))
        self.horizontalLayout_3.addWidget(self.btn_pst_del)
        self.verticalLayout_2.addWidget(self.frm_pst_bbx)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(dlgAerDataNEW)
        QtCore.QMetaObject.connectSlotsByName(dlgAerDataNEW)

    def retranslateUi(self, dlgAerDataNEW):
        dlgAerDataNEW.setWindowTitle(_translate("dlgAerDataNEW", "[ Edição de Aeródromos ]", None))
        self.btn_aer_new.setText(_translate("dlgAerDataNEW", "Novo", None))
        self.btn_aer_del.setText(_translate("dlgAerDataNEW", "Remove", None))
        self.lbl_aer_indc.setText(_translate("dlgAerDataNEW", "Indicativo:", None))
        self.txt_aer_indc.setText(_translate("dlgAerDataNEW", "STST", None))
        self.lbl_aer_desc.setText(_translate("dlgAerDataNEW", "Descrição:", None))
        self.qle_aer_desc.setText(_translate("dlgAerDataNEW", "Teste", None))
        self.gbx_arp.setTitle(_translate("dlgAerDataNEW", "ARP", None))
        self.lbl_elev.setText(_translate("dlgAerDataNEW", "Elevação:", None))
        self.lbl_lat.setText(_translate("dlgAerDataNEW", "Latitude:", None))
        self.lbl_lng.setText(_translate("dlgAerDataNEW", "Longitude:", None))
        self.qle_lat.setText(_translate("dlgAerDataNEW", "1961.19S", None))
        self.sbx_elev.setSuffix(_translate("dlgAerDataNEW", " m", None))
        self.lbl_decl.setText(_translate("dlgAerDataNEW", "Declinação Magnética:", None))
        self.dsb_decl.setSuffix(_translate("dlgAerDataNEW", " gr", None))
        self.qle_lng.setText(_translate("dlgAerDataNEW", "1970.02W", None))
        self.gbx_pst.setTitle(_translate("dlgAerDataNEW", "Pistas", None))
        self.btn_pst_new.setText(_translate("dlgAerDataNEW", "Novo", None))
        self.btn_pst_del.setText(_translate("dlgAerDataNEW", "Remove", None))

import qrc_resources_rc
